version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 65
      statements: 40
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - unnecessaryBlock
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 10
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godot
          - paralleltest
        path: integration-test
      - linters:
          - godot
        path: internal/controller/http
    paths:
      - bin/
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - bin/
      - third_party$
      - builtin$
      - examples$
